name: Generate Datasets (Weekly Cron Job)

on:
  # A new interval every Sunday (midnight)
  schedule:
    - cron: 0 0 * * 0 # 00:00 UTC
  push:
    branches:
      # Allows us to test this workflow
      - "generate-datasets-trigger-*"

jobs:
  citizens:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sources/citizens/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: data-sources/citizens/package-lock.json
      
      - name: Install Node.js Packages 🔧
        run: npm install

        # Generate Citizen Count CSV 🧮
      - run: npx tsc generate-citizen-count-csv.ts
      - run: node generate-citizen-count-csv.js

        # Generate Citizen Data CSV 🧮
      - run: npx tsc generate-citizens-csv.ts
      - run: node generate-citizens-csv.js

        # Generate Citizen Data JSON 🧮
      - run: npx tsc generate-citizens-json.ts
      - run: node generate-citizens-json.js

        # Generate Historical Citizen Data CSVs 🧮
      - run: npx tsc generate-voting-power-datasets.ts
      - run: node generate-voting-power-datasets.js

      - name: Set Environment Variables for PR
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Generated Citizens datasets for week ending $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="This PR was auto-generated on $(date +%Y-%m-%d)."
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"

      - name: Create commit and PR for the changes
        id: pr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: generated-datasets
          branch-suffix: timestamp
          commit-message: generate citizens datasets
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}

  sourcecred:
    needs: citizens
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sources/sourcecred/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: data-sources/sourcecred/package-lock.json
      
      - name: Install Node.js Packages 🔧
        run: npm install

      - run: npm run build
      - run: npm run generate

      - name: Set Environment Variables for PR
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Generated SourceCred datasets for week ending $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="This PR was auto-generated on $(date +%Y-%m-%d)."
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"

      - name: Create commit and PR for the changes
        id: pr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: generated-datasets
          branch-suffix: timestamp
          commit-message: generate sourcecred datasets
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}

  dework:
    needs: citizens
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sources/dework/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: data-sources/dework/package-lock.json
      
      - name: Install Node.js Packages 🔧
        run: npm install

      - run: npm run build
      - run: npm run generate

      - name: Set Environment Variables for PR
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Generated Dework datasets for week ending $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="This PR was auto-generated on $(date +%Y-%m-%d)."
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"

      - name: Create commit and PR for the changes
        id: pr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: generated-datasets
          branch-suffix: timestamp
          commit-message: generate dework datasets
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}

  karma:
    needs: citizens
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-sources/karma/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: data-sources/karma/package-lock.json
      
      - name: Install Node.js Packages 🔧
        run: npm install

      - run: npm run build
      - run: npm run generate

      - name: Set Environment Variables for PR
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Generated Karma datasets for week ending $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="This PR was auto-generated on $(date +%Y-%m-%d)."
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"

      - name: Create commit and PR for the changes
        id: pr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: generated-datasets
          branch-suffix: timestamp
          commit-message: generate karma datasets
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}

  nationcred:
    needs: sourcecred
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nationcred/
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: nationcred/package-lock.json
      
      - name: Install Node.js Packages 🔧
        run: npm install

      - run: npm run build
      - run: npm run generate

      - name: Set Environment Variables for PR
        id: pr_details
        run: |
          echo "PULL_REQUEST_TITLE=Generated NationCred datasets for week ending $(date +"%B %dth, %Y")" >> $GITHUB_ENV
          description="This PR was auto-generated on $(date +%Y-%m-%d)."
          description="${description//'%'/'%25'}"
          description="${description//$'\n'/'%0A'}"
          description="${description//$'\r'/'%0D'}"
          echo "::set-output name=pr_body::$description"

      - name: Create commit and PR for the changes
        id: pr
        uses: peter-evans/create-pull-request@v4.2.0
        with:
          branch: generated-datasets
          branch-suffix: timestamp
          commit-message: generate nationcred datasets
          title: ${{ env.PULL_REQUEST_TITLE }}
          body: ${{ steps.pr_details.outputs.pr_body }}
